development:
  adapter: postgresql
  database: receta_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: receta_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: receta_production
  pool: 5
  timeout: 5000