# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03e55a3ec4151af7a243d4eb2a75a5227fdb5762a40afa5fcf4ec1a696fc62306bda6c3dccf0c6c8e2defed34782558127663a64fb2aef429da0c38d0b0f5526

test:
  secret_key_base: 5afba0ba5ae7538aed655af98aa3c379ee26255f7ff4ce56973656ad8b5dad4482aeb9eb5037874dd3b393cd44550e42e9a83a01d1783f97e17de110207cb9b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
